export interface Theme {
  id: string;
  name: string;
  bgClass: string;
  cardClass: string;
  textClass: string;
  avatarClass: string;
  footerClass: string;
  preview: { bg: string; card: string; text: string };
}

export const themes: Record<string, Theme> = {
  default: {
    id: "default",
    name: "Default",
    bgClass: "bg-white",
    cardClass: "bg-indigo-600 text-white hover:bg-indigo-700 border-0",
    textClass: "text-slate-900",
    avatarClass: "ring-4 ring-indigo-200",
    footerClass: "text-slate-600",
    preview: { bg: "#ffffff", card: "#4f46e5", text: "#0f172a" },
  },
  midnight: {
    id: "midnight",
    name: "Midnight",
    bgClass: "bg-[#0f172a]",
    cardClass: "bg-cyan-500/10 text-cyan-100 hover:bg-cyan-500/20 border border-cyan-500/30",
    textClass: "text-white",
    avatarClass: "ring-4 ring-cyan-500/40",
    footerClass: "text-slate-400",
    preview: { bg: "#0f172a", card: "#164e63", text: "#ffffff" },
  },
  sunset: {
    id: "sunset",
    name: "Sunset",
    bgClass: "bg-gradient-to-br from-orange-400 via-pink-500 to-purple-600",
    cardClass: "bg-white/20 text-white hover:bg-white/30 border border-white/20 backdrop-blur-sm",
    textClass: "text-white",
    avatarClass: "ring-4 ring-white/40",
    footerClass: "text-white/70",
    preview: { bg: "#f97316", card: "#ffffff33", text: "#ffffff" },
  },
  forest: {
    id: "forest",
    name: "Forest",
    bgClass: "bg-[#064e3b]",
    cardClass: "bg-emerald-400/20 text-emerald-50 hover:bg-emerald-400/30 border border-emerald-400/30",
    textClass: "text-emerald-50",
    avatarClass: "ring-4 ring-emerald-400/40",
    footerClass: "text-emerald-300/60",
    preview: { bg: "#064e3b", card: "#34d39933", text: "#ecfdf5" },
  },
  neon: {
    id: "neon",
    name: "Neon",
    bgClass: "bg-black",
    cardClass: "bg-transparent text-[#39ff14] hover:bg-[#39ff14]/10 border border-[#39ff14]/60 shadow-[0_0_12px_rgba(57,255,20,0.3)]",
    textClass: "text-[#39ff14]",
    avatarClass: "ring-4 ring-[#39ff14]/50",
    footerClass: "text-[#39ff14]/70",
    preview: { bg: "#000000", card: "#39ff1433", text: "#39ff14" },
  },
  pastel: {
    id: "pastel",
    name: "Pastel",
    bgClass: "bg-violet-100",
    cardClass: "bg-gradient-to-r from-pink-300 to-blue-300 text-white hover:from-pink-400 hover:to-blue-400 border-0",
    textClass: "text-violet-900",
    avatarClass: "ring-4 ring-pink-300/50",
    footerClass: "text-violet-400",
    preview: { bg: "#ede9fe", card: "#f9a8d4", text: "#4c1d95" },
  },
  minimal: {
    id: "minimal",
    name: "Minimal",
    bgClass: "bg-white",
    cardClass: "bg-white text-black hover:bg-gray-100 border border-gray-200",
    textClass: "text-black",
    avatarClass: "ring-2 ring-gray-200",
    footerClass: "text-gray-500",
    preview: { bg: "#ffffff", card: "#f3f4f6", text: "#000000" },
  },
  glass: {
    id: "glass",
    name: "Glass",
    bgClass: "bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900",
    cardClass: "bg-white/10 text-white hover:bg-white/20 border border-white/10 backdrop-blur-md",
    textClass: "text-white",
    avatarClass: "ring-4 ring-white/20",
    footerClass: "text-white/70",
    preview: { bg: "#1e1b4b", card: "#ffffff1a", text: "#ffffff" },
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    bgClass: "bg-gradient-to-b from-blue-900 via-blue-800 to-cyan-900",
    cardClass: "bg-cyan-500/20 backdrop-blur-sm border border-cyan-400/30 text-white",
    textClass: "text-white",
    avatarClass: "ring-2 ring-cyan-400",
    footerClass: "text-cyan-300/50",
    preview: { bg: "#1e3a5f", card: "#0e7490", text: "#ffffff" },
  },
  candy: {
    id: "candy",
    name: "Candy",
    bgClass: "bg-gradient-to-br from-pink-400 via-purple-400 to-indigo-400",
    cardClass: "bg-white/25 backdrop-blur-sm border border-white/40 text-white",
    textClass: "text-white",
    avatarClass: "ring-2 ring-white/60",
    footerClass: "text-white/40",
    preview: { bg: "#ec4899", card: "#ffffff40", text: "#ffffff" },
  },
  retro: {
    id: "retro",
    name: "Retro",
    bgClass: "bg-amber-50",
    cardClass: "bg-amber-100 border-2 border-amber-800 text-amber-900 shadow-[3px_3px_0_#92400e]",
    textClass: "text-amber-900",
    avatarClass: "ring-2 ring-amber-800",
    footerClass: "text-amber-700/50",
    preview: { bg: "#fffbeb", card: "#fef3c7", text: "#78350f" },
  },
  cyberpunk: {
    id: "cyberpunk",
    name: "Cyberpunk",
    bgClass: "bg-gray-950",
    cardClass: "bg-fuchsia-500/10 border border-fuchsia-500/50 text-fuchsia-300 hover:shadow-fuchsia-500/20",
    textClass: "text-fuchsia-300",
    avatarClass: "ring-2 ring-fuchsia-500",
    footerClass: "text-fuchsia-500/30",
    preview: { bg: "#030712", card: "#d946ef20", text: "#f0abfc" },
  },
  nature: {
    id: "nature",
    name: "Nature",
    bgClass: "bg-gradient-to-b from-green-900 to-emerald-800",
    cardClass: "bg-emerald-600/20 backdrop-blur-sm border border-emerald-500/30 text-emerald-100",
    textClass: "text-emerald-100",
    avatarClass: "ring-2 ring-emerald-400",
    footerClass: "text-emerald-400/40",
    preview: { bg: "#14532d", card: "#059669", text: "#d1fae5" },
  },
  lavender: {
    id: "lavender",
    name: "Lavender",
    bgClass: "bg-gradient-to-b from-violet-100 to-purple-100",
    cardClass: "bg-white/70 backdrop-blur-sm border border-violet-200 text-violet-900",
    textClass: "text-violet-900",
    avatarClass: "ring-2 ring-violet-400",
    footerClass: "text-violet-400/50",
    preview: { bg: "#ede9fe", card: "#ffffff", text: "#4c1d95" },
  },
  monochrome: {
    id: "monochrome",
    name: "Monochrome",
    bgClass: "bg-neutral-100",
    cardClass: "bg-neutral-900 text-neutral-100",
    textClass: "text-neutral-900",
    avatarClass: "ring-2 ring-neutral-900",
    footerClass: "text-neutral-400",
    preview: { bg: "#f5f5f5", card: "#171717", text: "#171717" },
  },
  tokyo: {
    id: "tokyo",
    name: "Tokyo Night",
    bgClass: "bg-[#1a1b26]",
    cardClass: "bg-[#24283b] border border-[#414868] text-[#c0caf5]",
    textClass: "text-[#c0caf5]",
    avatarClass: "ring-2 ring-[#7aa2f7]",
    footerClass: "text-[#565f89]",
    preview: { bg: "#1a1b26", card: "#24283b", text: "#c0caf5" },
  },
  rose: {
    id: "rose",
    name: "Rose Gold",
    bgClass: "bg-gradient-to-b from-rose-50 to-pink-50",
    cardClass: "bg-white/80 backdrop-blur-sm border border-rose-200 text-rose-900",
    textClass: "text-rose-900",
    avatarClass: "ring-2 ring-rose-400",
    footerClass: "text-rose-300",
    preview: { bg: "#fff1f2", card: "#ffffff", text: "#881337" },
  },
  dark: {
    id: "dark",
    name: "Dark Mode",
    bgClass: "bg-zinc-950",
    cardClass: "bg-zinc-800 border border-zinc-700 text-zinc-100",
    textClass: "text-zinc-100",
    avatarClass: "ring-2 ring-zinc-500",
    footerClass: "text-zinc-600",
    preview: { bg: "#09090b", card: "#27272a", text: "#f4f4f5" },
  },
  aurora: {
    id: "aurora",
    name: "Aurora",
    bgClass: "bg-gradient-to-br from-emerald-900 via-teal-800 to-cyan-900",
    cardClass: "bg-white/10 backdrop-blur-md border border-white/20 text-white",
    textClass: "text-white",
    avatarClass: "ring-2 ring-teal-400",
    footerClass: "text-teal-300/40",
    preview: { bg: "#064e3b", card: "#ffffff20", text: "#ffffff" },
  },
  brutalist: {
    id: "brutalist",
    name: "Brutalist",
    bgClass: "bg-white",
    cardClass: "bg-white border-4 border-black text-black shadow-[6px_6px_0_#000] hover:shadow-[2px_2px_0_#000] transition-shadow",
    textClass: "text-black",
    avatarClass: "ring-4 ring-black",
    footerClass: "text-gray-400",
    preview: { bg: "#ffffff", card: "#ffffff", text: "#000000" },
  },
  warmth: {
    id: "warmth",
    name: "Warmth",
    bgClass: "bg-gradient-to-b from-orange-50 to-yellow-50",
    cardClass: "bg-white/80 border border-orange-200 text-orange-900 shadow-sm",
    textClass: "text-orange-900",
    avatarClass: "ring-2 ring-orange-400",
    footerClass: "text-orange-300",
    preview: { bg: "#fff7ed", card: "#ffffff", text: "#7c2d12" },
  },
};

export function getTheme(id: string): Theme {
  return themes[id] ?? themes.default;
}

export const themeList = Object.values(themes);
